### ISSUE TITLE
Config Prettier

### ISSUE THREAD

**Issue by N3v1** [Venkateeshh/Metro-Shortest-Path#2]
Hi @Venkateeshh,
I would recommend using a code formatter to publish well formatted code

I can config Prettier for you - Please assign this issue to me

**Comment by Venkateeshh** [comment]
Hi @N3v1 👋,
Config Prettier for HTML, CSS, and JS if it is possible

Best regards
Venkateeshh

**Comment by N3v1** [comment]
Thanks @Venkateeshh

**Comment by Venkateeshh** [comment]
@N3v1 when can i see the changes ?

**Comment by N3v1** [comment]
I'll start working on it on Friday @Venkateeshh

**Comment by Venkateeshh** [comment]
@N3v1 can I expect it by EOD?

**Comment by N3v1** [comment]
See #3
